<?php
declare(strict_types=1);

// Writable user-data store. Deliberately kept OUTSIDE the web root:
//   - public/data/ui.db is regenerated by tools/build_ui_db.py and re-uploaded, so
//     anything stored there is destroyed on the next data refresh;
//   - public/data/ is directly fetchable over HTTP, and this file holds private notes.
//
// Layout on a shared host, where public/ is uploaded as the web root:
//   <web root>/              → public/
//   <web root>/../private/   → app.db, secret.key
//
// Override the location by creating public/api/config.local.php (gitignored) with
//   <?php define('OTIOS_PRIVATE_DIR', '/home/you/otios-private');

require_once __DIR__ . '/_lib.php';

if (is_file(__DIR__ . '/config.local.php')) {
    require_once __DIR__ . '/config.local.php';
}
if (!defined('OTIOS_PRIVATE_DIR')) {
    define('OTIOS_PRIVATE_DIR', dirname(__DIR__, 2) . '/private');
}
define('APP_DB_PATH', OTIOS_PRIVATE_DIR . '/app.db');

const APP_DB_VERSION = 4;

// The annotation buckets a user actually produces, and the annotated_words_subquery()
// argument that selects each. A published list is a snapshot of one of these, which is why
// `lists.source_tag` stores a key from here — it is what "actualizează" re-reads.
//
// **Three, not four: `ascunde` is retired.** It said the same thing as `meh` ("not what I
// am looking for") with a harsher name, and its button is already commented out of
// detail.php. The tag itself is *not* forgotten — `api/quiz.php` still reads `tag:ascunde`
// literally when picking distractors, and old annotations keep working — it simply is no
// longer a bucket you can publish. A list already published from it keeps its row and its
// words; it loses only "actualizează", which is what retiring the source means.
const LIST_BUCKETS = [
    'fav' => ['marks' => 'bookmarked', 'emoji' => '★',  'label' => 'favorite'],
    'lol' => ['marks' => 'tag:lol',    'emoji' => '😂', 'label' => 'lol'],
    'meh' => ['marks' => 'tag:meh',    'emoji' => '😐', 'label' => 'meh'],
];

// Input caps. Enforced server-side so the API can't be used as free storage.
const MAX_NOTE_LEN      = 2000;
const MAX_TAGS_PER_WORD = 20;
const MAX_TAG_LEN       = 40;
const MAX_WORDS_PER_USER = 20000;
const MAX_LISTS_PER_USER = 50;
const MAX_WORDS_PER_LIST = 1000;
const MAX_REPORT_REASON_LEN = 500;

function private_dir(): string {
    if (!is_dir(OTIOS_PRIVATE_DIR)) {
        @mkdir(OTIOS_PRIVATE_DIR, 0770, true);
    }
    return OTIOS_PRIVATE_DIR;
}

/**
 * Secret for signing quiz questions. Generated once on first use so the app is
 * zero-config on a shared host; override with OTIOS_QUIZ_SECRET in config.local.php.
 */
function app_secret(): string {
    static $secret = null;
    if ($secret !== null) return $secret;
    if (defined('OTIOS_QUIZ_SECRET')) return $secret = (string) OTIOS_QUIZ_SECRET;

    $path = private_dir() . '/secret.key';
    if (is_file($path)) {
        $secret = trim((string) file_get_contents($path));
        if ($secret !== '') return $secret;
    }
    $secret = bin2hex(random_bytes(32));
    file_put_contents($path, $secret, LOCK_EX);
    @chmod($path, 0600);
    return $secret;
}

/**
 * Write connection to app.db. Separate from db(), which sets `query_only = ON`
 * connection-wide for ui.db and therefore cannot be reused for writes.
 */
function app_db(): PDO {
    static $pdo = null;
    if ($pdo !== null) return $pdo;

    private_dir();
    $fresh = !is_file(APP_DB_PATH);
    $pdo = new PDO('sqlite:' . APP_DB_PATH, null, null, [
        PDO::ATTR_ERRMODE            => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
    ]);

    // WAL needs a working shared-memory file; some NFS-backed shared hosts can't do
    // it and silently stay in `delete` mode. Fall back rather than fail.
    $mode = (string) $pdo->query('PRAGMA journal_mode = WAL')->fetchColumn();
    if (strtolower($mode) !== 'wal') {
        $pdo->exec('PRAGMA journal_mode = TRUNCATE');
    }
    $pdo->exec('PRAGMA busy_timeout = 5000');
    $pdo->exec('PRAGMA foreign_keys = ON');
    if ($fresh) @chmod(APP_DB_PATH, 0600);

    app_db_migrate($pdo);
    return $pdo;
}

/**
 * Attach app.db to the read-only ui.db connection, so a query can join a user's
 * annotations against the word table in one statement instead of shipping the whole
 * bookmark list through the URL.
 *
 * The read connection keeps `query_only = ON`, which covers attached databases too —
 * writes still have to go through app_db(). Returns false if app.db does not exist
 * yet, in which case the caller should treat the user as having no annotations.
 */
function attach_app_db(): bool {
    static $ok = null;
    if ($ok !== null) return $ok;
    if (!is_file(APP_DB_PATH)) return $ok = false;

    try {
        db()->exec("ATTACH DATABASE '" . str_replace("'", "''", APP_DB_PATH) . "' AS app");
        return $ok = true;
    } catch (Throwable $e) {
        return $ok = false;
    }
}

/**
 * SQL fragment selecting the words a user has annotated in a particular way, for use
 * as `word IN (...)` / `word NOT IN (...)`. Returns [sql, params] or null if the
 * marks value needs no annotation lookup.
 */
function annotated_words_subquery(string $marks, int $user_id): ?array {
    $base = 'SELECT word FROM app.annotations WHERE user_id = ? AND deleted = 0';
    $any  = "(bookmarked = 1 OR TRIM(note) != '' OR (tags != '[]' AND tags != ''))";

    if ($marks === 'bookmarked') return ["$base AND bookmarked = 1", [$user_id]];
    if ($marks === 'noted')      return ["$base AND TRIM(note) != ''", [$user_id]];
    if ($marks === 'marked' || $marks === 'unmarked') return ["$base AND $any", [$user_id]];

    if (str_starts_with($marks, 'tag:')) {
        $tag = trim(substr($marks, 4));
        if ($tag === '') return null;
        // tags is a JSON array of strings; the surrounding quotes make a LIKE match
        // exact ("funny" cannot match "funnyfoo"). Avoids depending on the JSON1
        // extension being compiled in on the host.
        $needle = '%"' . str_replace(['\\', '%', '_'], ['\\\\', '\%', '\_'], $tag) . '"%';
        return ["$base AND tags LIKE ? ESCAPE '\\'", [$user_id, $needle]];
    }
    return null;
}

/**
 * Per-word community vote counts, as a joinable `SELECT word, votes` fragment.
 *
 * **One user is one vote.** The annotations PK is (user_id, word), so there is exactly
 * one row per person per word and a plain SUM is already a distinct-user count. A word
 * someone both favourited and lol'd counts once, which matches the marking loop's own
 * "one mark per word is the intended interaction" — see the Lists section of CLAUDE.md.
 *
 * ★ and 😂 are +1, ⚠️ meh is −1, 🙈 ascunde is not a vote (it is "get this out of my
 * way", not a judgement about the word). A row carrying both a positive mark and meh
 * counts positive: the explicit ★ is the more deliberate of the two.
 *
 * This never filters anything. Community marks may only reorder — see the `populare`
 * entry in $SORT_OPTIONS. Identity here is an anonymous device token, so N votes cost
 * N cookie clears; letting them subtract would make hiding a word cheaper than
 * publishing a list, which is the same reasoning that kept auto-hide-after-N-reports
 * out of list moderation below.
 *
 * The '%"lol"%' quoting is annotated_words_subquery()'s convention: the quotes make the
 * match exact, so `lol` cannot match a custom tag like `lolz`.
 *
 * The key column is aliased `vote_word` on purpose. Joined against `words` it would
 * otherwise make every unqualified `word` in build_word_filter()'s conditions ambiguous,
 * and those conditions are shared with the un-joined query — so the alternative is
 * qualifying every one of them for the benefit of a single sort.
 */
function vote_counts_subquery(): string {
    return "SELECT word AS vote_word,
                   SUM(CASE
                         WHEN bookmarked = 1 OR tags LIKE '%\"lol\"%' THEN  1
                         WHEN tags LIKE '%\"meh\"%'                   THEN -1
                         ELSE 0
                       END) AS votes
              FROM app.annotations
             WHERE deleted = 0
             GROUP BY word";
}

/**
 * Idempotent migrations keyed on PRAGMA user_version. Runs on connect because a
 * shared host may offer no usable CLI to run a setup script.
 */
function app_db_migrate(PDO $pdo): void {
    $version = (int) $pdo->query('PRAGMA user_version')->fetchColumn();
    if ($version >= APP_DB_VERSION) return;

    if ($version < 1) {
        $pdo->exec(<<<'SQL'
CREATE TABLE IF NOT EXISTS users (
    id            INTEGER PRIMARY KEY,
    public_id     TEXT NOT NULL UNIQUE,
    nickname      TEXT,
    email         TEXT UNIQUE,
    auth_provider TEXT,
    auth_subject  TEXT,
    created_at    TEXT NOT NULL,
    last_seen_at  TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_auth ON users(auth_provider, auth_subject)
    WHERE auth_provider IS NOT NULL;

CREATE TABLE IF NOT EXISTS devices (
    id           INTEGER PRIMARY KEY,
    user_id      INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash   TEXT NOT NULL UNIQUE,
    user_agent   TEXT,
    created_at   TEXT NOT NULL,
    last_seen_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_devices_user ON devices(user_id);

-- `seq` is a per-user monotonic counter and is what the delta cursor reads.
-- Wall-clock time cannot serve as the cursor: PHP's gmdate() has no sub-second
-- precision, so two changes in the same second would be indistinguishable and the
-- `> since` comparison would silently skip one. `updated_at` still decides
-- last-write-wins, where client clock skew is acceptable.
CREATE TABLE IF NOT EXISTS annotations (
    user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    word       TEXT NOT NULL,
    bookmarked INTEGER NOT NULL DEFAULT 0,
    note       TEXT NOT NULL DEFAULT '',
    tags       TEXT NOT NULL DEFAULT '[]',
    updated_at TEXT NOT NULL,
    seq        INTEGER NOT NULL DEFAULT 0,
    deleted    INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (user_id, word)
);
CREATE INDEX IF NOT EXISTS idx_annotations_delta ON annotations(user_id, seq);

CREATE TABLE IF NOT EXISTS lists (
    id          INTEGER PRIMARY KEY,
    user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    slug        TEXT NOT NULL UNIQUE,
    title       TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    is_public   INTEGER NOT NULL DEFAULT 0,
    item_count  INTEGER NOT NULL DEFAULT 0,
    created_at  TEXT NOT NULL,
    updated_at  TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_lists_user ON lists(user_id);

CREATE TABLE IF NOT EXISTS list_items (
    list_id  INTEGER NOT NULL REFERENCES lists(id) ON DELETE CASCADE,
    word     TEXT NOT NULL,
    position INTEGER NOT NULL DEFAULT 0,
    note     TEXT NOT NULL DEFAULT '',
    added_at TEXT NOT NULL,
    PRIMARY KEY (list_id, word)
);

-- Append-only answer log: the substrate for leaderboards, per-word difficulty and
-- spaced repetition. game_stats below is a derived cache, rebuildable from this.
CREATE TABLE IF NOT EXISTS game_events (
    id         INTEGER PRIMARY KEY,
    user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    mode       TEXT NOT NULL,
    word       TEXT NOT NULL,
    chosen     TEXT NOT NULL DEFAULT '',
    correct    INTEGER NOT NULL,
    ms         INTEGER,
    created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_events_user ON game_events(user_id, created_at);
CREATE INDEX IF NOT EXISTS idx_events_word ON game_events(word);

CREATE TABLE IF NOT EXISTS game_stats (
    user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    mode        TEXT NOT NULL,
    streak      INTEGER NOT NULL DEFAULT 0,
    best_streak INTEGER NOT NULL DEFAULT 0,
    total       INTEGER NOT NULL DEFAULT 0,
    correct     INTEGER NOT NULL DEFAULT 0,
    updated_at  TEXT NOT NULL,
    PRIMARY KEY (user_id, mode)
);
CREATE INDEX IF NOT EXISTS idx_stats_best ON game_stats(mode, best_streak DESC);

CREATE TABLE IF NOT EXISTS feed_decisions (
    user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    word       TEXT NOT NULL,
    decision   TEXT NOT NULL,
    created_at TEXT NOT NULL,
    PRIMARY KEY (user_id, word)
);

CREATE TABLE IF NOT EXISTS quiz_nonces (
    nonce   TEXT PRIMARY KEY,
    used_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_nonces_used ON quiz_nonces(used_at);

CREATE TABLE IF NOT EXISTS rate_limits (
    user_id      INTEGER NOT NULL,
    bucket       TEXT NOT NULL,
    window_start INTEGER NOT NULL,
    count        INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (user_id, bucket)
);
SQL);
    }

    if ($version < 2) {
        // Which bucket a list was published from, so it can be re-synced later. '' is
        // "assembled by hand" — every list that existed before this column did.
        try {
            $pdo->exec("ALTER TABLE lists ADD COLUMN source_tag TEXT NOT NULL DEFAULT ''");
        } catch (PDOException $e) {
            // Already added by a concurrent request; the column is what matters, not who won.
            if (!str_contains($e->getMessage(), 'duplicate column')) throw $e;
        }
    }

    if ($version < 3) {
        // Takedown path for the public list directory. `status` is the whole workflow:
        // a report is `open` until someone reviews it, then `dismissed` (the list was
        // fine) or `removed` (the list was unpublished).
        //
        // Note there is deliberately NO auto-hide-on-N-reports rule. Identity here is an
        // anonymous device token, so "three different users reported this" costs an
        // abuser three cookie clears — a report threshold would be a cheaper way to
        // censor a list than to publish one. Reports queue for a human instead.
        $pdo->exec(<<<'SQL'
CREATE TABLE IF NOT EXISTS reports (
    id          INTEGER PRIMARY KEY,
    list_id     INTEGER NOT NULL REFERENCES lists(id) ON DELETE CASCADE,
    user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    reason      TEXT NOT NULL DEFAULT '',
    status      TEXT NOT NULL DEFAULT 'open',
    created_at  TEXT NOT NULL,
    resolved_at TEXT
);
-- One report per person per list: re-reporting shouldn't inflate the queue.
CREATE UNIQUE INDEX IF NOT EXISTS idx_reports_once ON reports(list_id, user_id);
CREATE INDEX IF NOT EXISTS idx_reports_queue ON reports(status, created_at);
SQL);
    }

    if ($version < 4) {
        // vote_counts_subquery() groups by word across every user. The only other index
        // is (user_id, seq) for the sync delta, which cannot serve that — so without
        // this the `populare` sort full-scans annotations on every request.
        $pdo->exec('CREATE INDEX IF NOT EXISTS idx_annotations_word ON annotations(word)');
    }

    $pdo->exec('PRAGMA user_version = ' . APP_DB_VERSION);
}

/**
 * The words in one of a user's four buckets, newest annotation first.
 *
 * Reads app.db directly rather than through attach_app_db(), because the caller may be a
 * write path already holding the app_db() connection. Words are not filtered against
 * ui.db here — filter_existing_words() does that where it matters.
 */
function bucket_words(int $user_id, string $bucket): array {
    if (!isset(LIST_BUCKETS[$bucket])) return [];

    $sub = annotated_words_subquery(LIST_BUCKETS[$bucket]['marks'], $user_id);
    if ($sub === null) return [];

    // annotated_words_subquery() names the table `app.annotations` for the attached
    // read connection; on the direct write connection it is just `annotations`.
    [$sql, $params] = $sub;
    $sql = str_replace('app.annotations', 'annotations', $sql);

    $stmt = app_db()->prepare("$sql ORDER BY updated_at DESC");
    $stmt->execute($params);
    return $stmt->fetchAll(PDO::FETCH_COLUMN);
}

// Fixed-width UTC with milliseconds, so timestamps compare correctly as plain strings
// in SQLite. Millisecond precision matters for last-write-wins: gmdate() would pin
// every timestamp to whole seconds, making same-second edits indistinguishable.
const TS_FORMAT = 'Y-m-d\TH:i:s.v\Z';

function now_iso(): string {
    return (new DateTimeImmutable('now', new DateTimeZone('UTC')))->format(TS_FORMAT);
}

// ── Sealed tokens ─────────────────────────────────────────────────────────────
//
// Carries a quiz question's answer through the browser and back without keeping
// server-side session state, which a shared host with no persistent process makes
// awkward.
//
// This must be ENCRYPTED, not merely signed: an HMAC-signed payload is unforgeable
// but perfectly readable, so base64-decoding the token would hand out the answer.
// AES-256-GCM gives confidentiality and authenticity in one step — a tampered token
// fails to decrypt at all.

function b64url(string $bin): string {
    return rtrim(strtr(base64_encode($bin), '+/', '-_'), '=');
}

function token_key(): string {
    return hash('sha256', app_secret(), true);
}

function seal_token(array $payload): string {
    $iv  = random_bytes(12);
    $tag = '';
    $ct  = openssl_encrypt(
        json_encode($payload, JSON_UNESCAPED_UNICODE),
        'aes-256-gcm', token_key(), OPENSSL_RAW_DATA, $iv, $tag
    );
    if ($ct === false) throw new RuntimeException('seal failed');
    return b64url($iv . $tag . $ct);
}

/** Returns null if the token is malformed, tampered with, or expired. */
function open_token(string $token, int $max_age = 900): ?array {
    $raw = base64_decode(strtr($token, '-_', '+/'), true);
    if ($raw === false || strlen($raw) <= 28) return null;

    $json = openssl_decrypt(
        substr($raw, 28), 'aes-256-gcm', token_key(), OPENSSL_RAW_DATA,
        substr($raw, 0, 12), substr($raw, 12, 16)
    );
    if ($json === false) return null;

    $data = json_decode($json, true);
    if (!is_array($data) || !isset($data['t'])) return null;
    if (time() - (int) $data['t'] > $max_age) return null;

    return $data;
}

/**
 * Single-use enforcement for signed tokens. Without this a valid winning token could
 * be replayed to inflate a streak. Old rows are pruned opportunistically so the table
 * needs no cron job.
 */
function consume_nonce(string $nonce): bool {
    $pdo  = app_db();
    $stmt = $pdo->prepare('INSERT OR IGNORE INTO quiz_nonces (nonce, used_at) VALUES (?, ?)');
    $stmt->execute([$nonce, now_iso()]);
    $fresh = $stmt->rowCount() > 0;

    if (random_int(1, 100) === 1) {
        $pdo->prepare('DELETE FROM quiz_nonces WHERE used_at < ?')
            ->execute([(new DateTimeImmutable('-1 hour', new DateTimeZone('UTC')))->format(TS_FORMAT)]);
    }
    return $fresh;
}

/** Blank out the target word inside a definition so it can't give the answer away. */
function mask_word(string $text, string $word): string {
    if ($word === '') return $text;
    return (string) preg_replace('/' . preg_quote($word, '/') . '/iu', '———', $text);
}

/**
 * Keep only words that actually exist in ui.db, so the API can't be turned into
 * arbitrary key-value storage. Chunked to stay under SQLite's variable limit.
 */
function filter_existing_words(array $words): array {
    $words = array_values(array_unique(array_filter($words, fn($w) => is_string($w) && $w !== '')));
    if ($words === []) return [];

    $found = [];
    foreach (array_chunk($words, 400) as $chunk) {
        $ph   = implode(',', array_fill(0, count($chunk), '?'));
        $stmt = db()->prepare("SELECT word FROM words WHERE word IN ($ph)");
        $stmt->execute($chunk);
        foreach ($stmt->fetchAll(PDO::FETCH_COLUMN) as $w) { $found[$w] = true; }
    }
    return $found;
}

/** Fixed-window rate limiter. Returns false when the caller is over budget. */
function rate_limit(int $user_id, string $bucket, int $max, int $window_sec): bool {
    $now    = time();
    $window = $now - ($now % $window_sec);
    $pdo    = app_db();

    $pdo->prepare(
        'INSERT INTO rate_limits (user_id, bucket, window_start, count) VALUES (?, ?, ?, 0)
         ON CONFLICT(user_id, bucket) DO UPDATE SET
            count        = CASE WHEN rate_limits.window_start < ? THEN 0 ELSE rate_limits.count END,
            window_start = CASE WHEN rate_limits.window_start < ? THEN ?  ELSE rate_limits.window_start END'
    )->execute([$user_id, $bucket, $window, $window, $window, $window]);

    $stmt = $pdo->prepare('SELECT count FROM rate_limits WHERE user_id = ? AND bucket = ?');
    $stmt->execute([$user_id, $bucket]);
    if ((int) $stmt->fetchColumn() >= $max) return false;

    $pdo->prepare('UPDATE rate_limits SET count = count + 1 WHERE user_id = ? AND bucket = ?')
        ->execute([$user_id, $bucket]);
    return true;
}
