<?php
declare(strict_types=1);

// Snapshot private/app.db to a timestamped copy, and prune old ones.
//
// app.db is the only irreplaceable file in a deploy: ui.db is regenerated by
// tools/build_ui_db.py from the pipeline, but annotations, lists, nicknames and the
// game log exist nowhere else.
//
// This lives inside public/api/ for one reason: only the *contents of public/* are
// deployed (see "Deploying to a subfolder" in CLAUDE.md), so a script anywhere else in
// the repo simply is not on the server. It is CLI-only — the guard below is the first
// thing that runs, before any include.
//
//   php api/_backup.php                 # write a snapshot, keep the newest 14
//   php api/_backup.php --keep 30       # keep the newest 30
//   php api/_backup.php --dir /path     # write somewhere else (an external mount)
//   php api/_backup.php --list          # show what's there, write nothing
//
// Nightly cron, from the deployed app folder:
//   17 3 * * * cd ~/lab.gov2.ro/oțios && php api/_backup.php >> ~/otios-private/backup.log 2>&1

if (PHP_SAPI !== 'cli') {
    http_response_code(404);
    exit("Not Found\n");
}

require_once __DIR__ . '/_appdb.php';

$args = $argv ?? [];
$opt  = static function (string $name, ?string $default = null) use ($args): ?string {
    $i = array_search($name, $args, true);
    return $i !== false && isset($args[$i + 1]) ? (string) $args[$i + 1] : $default;
};

$keep     = max(1, (int) $opt('--keep', '14'));
$dest_dir = rtrim((string) $opt('--dir', OTIOS_PRIVATE_DIR . '/backups'), '/');
$list_only = in_array('--list', $args, true);

/** Newest first, so pruning is "everything after the first $keep". */
function existing_backups(string $dir): array {
    $found = glob($dir . '/app-*.db') ?: [];
    rsort($found, SORT_STRING);   // the timestamp format sorts lexicographically
    return $found;
}

if ($list_only) {
    $found = existing_backups($dest_dir);
    printf("%s — %d snapshot(s)\n", $dest_dir, count($found));
    foreach ($found as $f) {
        printf("  %s  %8.1f KB  %s\n", basename($f), filesize($f) / 1024, date('Y-m-d H:i', (int) filemtime($f)));
    }
    exit(0);
}

if (!is_file(APP_DB_PATH)) {
    fwrite(STDERR, "No database at " . APP_DB_PATH . " — nothing to back up.\n");
    exit(1);
}

if (!is_dir($dest_dir) && !@mkdir($dest_dir, 0700, true) && !is_dir($dest_dir)) {
    fwrite(STDERR, "Cannot create $dest_dir\n");
    exit(1);
}
@chmod($dest_dir, 0700);

// Read-only, and deliberately NOT app_db(): that helper runs migrations on connect,
// and a backup must never be the thing that changes the schema it is copying.
$src = new PDO('sqlite:' . APP_DB_PATH, null, null, [
    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
]);

// VACUUM INTO takes a consistent snapshot while other processes keep writing, which
// plain copy() cannot do: in WAL mode the committed data is split across app.db and
// app.db-wal, so a naive file copy can land mid-transaction and produce a torn file.
$sqlite_version = (string) $src->query('SELECT sqlite_version()')->fetchColumn();
if (version_compare($sqlite_version, '3.27.0', '<')) {
    fwrite(STDERR,
        "SQLite $sqlite_version is too old for VACUUM INTO (needs 3.27+).\n" .
        "Use the CLI instead:  sqlite3 " . APP_DB_PATH . " \".backup '<dest>'\"\n");
    exit(1);
}

$stamp = gmdate('Ymd-His');
$dest  = "$dest_dir/app-$stamp.db";

// VACUUM INTO refuses to overwrite, which is the behaviour we want — but it means a
// second run inside the same second is an error rather than a no-op. Treat it as the
// no-op it really is: there is already a snapshot of this second.
if (is_file($dest)) {
    printf("%s already exists — nothing to do.\n", basename($dest));
    exit(0);
}

try {
    $src->exec("VACUUM INTO " . $src->quote($dest));
} catch (PDOException $e) {
    fwrite(STDERR, "Backup failed: " . $e->getMessage() . "\n");
    exit(1);
}
@chmod($dest, 0600);

// A backup nobody has opened is a backup nobody knows is good.
$check = (new PDO('sqlite:' . $dest, null, null, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]))
    ->query('PRAGMA integrity_check')->fetchColumn();
if ($check !== 'ok') {
    fwrite(STDERR, "Integrity check FAILED on $dest: $check\n");
    exit(1);
}

printf("%s  %.1f KB  ok\n", basename($dest), filesize($dest) / 1024);

$pruned = 0;
foreach (array_slice(existing_backups($dest_dir), $keep) as $old) {
    if (@unlink($old)) $pruned++;
}
if ($pruned > 0) printf("pruned %d old snapshot(s), keeping %d\n", $pruned, $keep);
